csdn:
  api:
    categories: Java面试经验分享
    cookie: ${CSDN_COOKIE:}
    nonce: ${X_CA_NONCE:}
    signature: ${X_CA_SIGNATURE:}
  session:
    data-root: ./data
    fixed-session-id: default
    login-timeout-minutes: 10
    public-base-url: ${CSDN_PUBLIC_BASE_URL:http://127.0.0.1:18080}
  debug:
    enabled: false

spring:
  application:
    name: mcp-server-csdn
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        stdio: false
  mvc:
    async:
      request-timeout: -1
  main:
    banner-mode: off
    web-application-type: servlet

logging:
  level:
    root: INFO
  file:
    name: data/log/${spring.application.name}.log

server:
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
